spring.application.name=backend

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.liquibase.changelog=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true

logging.level.liquibase=DEBUG

spring.mvc.problemdetails.enabled=true

app.jwt.secret-key=${JWT_SECRET}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS}